In [1]:
import pandas
data = pandas.read_csv('UDC Grade Distribution 21-24.csv')
data

,Academic Year,Term,Subject,Course No.,Course Title,Instructor,GPA,A (%),A- (%),B+ (%),...,C (%),C- (%),D+ (%),D (%),D- (%),F (%),Withdraws,Graded Enrollment,CRN,Credits
0,2021-22,Fall,ECE,3274,Elctrnc Circuits Lab II,Cooper,3.82,40.0,60.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,5,83465,1
1,2021-22,Fall,ENSC,3124,Soils Laboratory,Mott,2.86,60.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,20.0,0,5,84840,1
2,2021-22,Fall,ENSC,3124,Soils Laboratory,Mott,2.68,40.0,20.0,0.0,...,0.0,20.0,0.0,0.0,0.0,20.0,0,5,84843,1
3,2021-22,Fall,ENSC,3124,Soils Laboratory,Mott,3.80,60.0,20.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,5,84844,1
4,2021-22,Fall,IDS,3234,TS: Studio Magazine,Pritchett,4.00,100.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,5,86114,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,2023-24,Fall,ITDS,1114,Design Appreciation,Tew,3.56,65.7,7.7,7.5,...,2.5,1.0,1.2,0.9,0.7,2.0,56,3074,86796,3
25075,2022-23,Spring,ITDS,1114,Design Appreciation,Tew,3.58,73.8,4.2,4.7,...,2.2,1.1,1.1,1.0,0.6,3.0,58,3199,16914,3
25076,2021-22,Spring,ITDS,1114,Design Appreciation,Tew,3.48,66.6,6.4,6.0,...,2.9,1.1,1.6,1.3,0.7,3.6,77,3334,16728,3
25077,2022-23,Fall,ITDS,1114,Design Appreciation,Tew,3.59,72.6,5.0,4.8,...,2.4,1.3,0.7,0.5,0.7,2.9,59,3358,86752,3
25078,2021-22,Fall,ITDS,1114,Design Appreciation,Tew,3.50,64.4,8.4,4.7,...,2.2,1.9,0.7,1.3,0.6,3.1,120,4135,86418,3

In [51]:
years = ['2021-22', '2022-23', '2023-24']
sems = ['Fall', 'Spring', 'Summer I', 'Summer II', 'Winter']
subject = 'CS'
course = '1114'
def parse_data(years, sems, subject=None, course=None):
    filtered_data = data[(data['Academic Year'].isin(years)) & (data['Term'].isin(sems))]

    if subject:
        filtered_data = filtered_data[(filtered_data['Subject'] == subject)]
    if course:
        filtered_data = filtered_data[(filtered_data['Course No.'] == int(course))]

    return filtered_data.sort_values('Course No.')

new_data = parse_data(years, sems, subject)

,Academic Year,Term,Subject,Course No.,Course Title,Instructor,GPA,A (%),A- (%),B+ (%),...,C (%),C- (%),D+ (%),D (%),D- (%),F (%),Withdraws,Graded Enrollment,CRN,Credits
22661,2022-23,Fall,CS,1014,Intro Computational Thinking,Kafura,3.44,42.2,29.7,1.6,...,6.3,1.6,0.0,1.6,0.0,1.6,4,64,83192,3
22637,2021-22,Fall,CS,1014,Intro Computational Thinking,Kafura,3.30,39.1,20.3,9.4,...,3.1,3.1,0.0,3.1,1.6,1.6,3,64,83013,3
22533,2021-22,Spring,CS,1014,Intro Computational Thinking,Kafura,3.00,29.0,14.5,9.7,...,4.8,6.5,0.0,1.6,1.6,4.8,4,62,13169,3
21776,2023-24,Fall,CS,1014,Intro Computational Thinking,Hillman,3.46,51.9,13.5,15.4,...,0.0,0.0,0.0,0.0,0.0,5.8,2,52,83275,3
21752,2022-23,Spring,CS,1014,Intro Computational Thinking,Hillman,2.52,7.7,13.5,17.3,...,7.7,3.8,1.9,5.8,3.8,9.6,5,52,13274,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10709,2022-23,Spring,CS,6804,TS: Multimodal Vision,Thomas,3.90,75.0,18.8,6.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0,16,21715,3
11393,2022-23,Spring,CS,6804,TS: Mach Learning on Graphs,Zhou,3.75,52.9,29.4,5.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0,17,20674,3
11277,2022-23,Fall,CS,6804,TS: Multisource Mach Learning,Eldardiry,3.87,70.6,23.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,17,90792,3
15206,2023-24,Fall,CS,6814,Science-Guided Mach Learning,Karpatne,3.96,87.0,13.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,23,91145,3
6292,2021-22,Spring,CS,6824,TS: AI-powered Molecular Mdlng,Bhattacharya,3.83,70.0,10.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,10,20577,3

In [62]:
def sort_data(data, year=False, sem=False, subject=False, course=False):
    sort_columns = []
    if year:
        sort_columns.append('Academic Year')
    if sem:
        sort_columns.append('Term')
    if subject:
        sort_columns.append('Subject')
    if course:
        sort_columns.append('Course No.')

    return data.sort_values(sort_columns)

new_data = parse_data(years, sems)
sorted_data = sort_data(new_data, True, True)
sorted_data

,Academic Year,Term,Subject,Course No.,Course Title,Instructor,GPA,A (%),A- (%),B+ (%),...,C (%),C- (%),D+ (%),D (%),D- (%),F (%),Withdraws,Graded Enrollment,CRN,Credits
11555,2021-22,Fall,AT,144,Communication Skills,Jeter,2.95,46.2,7.7,0.0,...,0.0,0.0,15.4,0.0,0.0,7.7,0,13,81263,4
10172,2021-22,Fall,AT,144,Communication Skills,Jeter,2.17,16.7,8.3,8.3,...,16.7,8.3,8.3,8.3,0.0,16.7,0,12,81261,4
13197,2021-22,Fall,AT,144,Communication Skills,Jeter,2.45,13.3,20.0,0.0,...,0.0,13.3,0.0,0.0,6.7,13.3,0,15,81262,4
18494,2021-22,Fall,AT,164,Introduction to Animal Science,Kohl,2.91,26.9,7.7,15.4,...,7.7,11.5,3.8,0.0,0.0,3.8,0,26,81266,4
10173,2021-22,Fall,AT,174,Fundamentals of Turfgrass Mgmt,Dickerson,2.25,0.0,8.3,16.7,...,16.7,16.7,8.3,0.0,0.0,8.3,0,12,81267,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,2023-24,Summer I,PAPA,6354,Adv Topics Pub Mgt,Davis,4.00,100.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,15,64744,3
10727,2023-24,Summer I,EDCO,6534,DSM Application in Counseling,Welfare,3.98,93.8,6.3,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,16,61887,3
9301,2023-24,Summer I,EDEL,6914,PR: OTR I,Brinkmann,4.00,100.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,14,61919,3
8042,2023-24,Summer I,EDEL,6914,PR: OTR II,Lowery,4.00,100.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,12,61921,3
6583,2023-24,Summer I,EDEL,6914,PR: OTR II,Lowery,4.00,100.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,10,61922,3

In [66]:
years = ['2021-22', '2022-23', '2023-24']
sems = ['Fall', 'Spring', 'Summer I', 'Summer II', 'Winter']
new_data = parse_data(years, sems)
subject_list = new_data['Subject'].unique()
subject_list

array(['AT', 'MN', 'COS', 'SOC', 'ISC', 'TA', 'UNIV', 'BIOL', 'EDCI',
       'NEUR', 'ALS', 'HNFE', 'HIST', 'ARCH', 'COMM', 'ECE', 'GEOS',
       'LAHS', 'PSCI', 'ART', 'IS', 'ENGL', 'UAP', 'HD', 'GEOG', 'MUS',
       'ACIS', 'SBIO', 'STAT', 'FREC', 'REAL', 'PPE', 'SPES', 'EDTE',
       'AAD', 'MSE', 'PSYC', 'CHEM', 'CAUS', 'RLCL', 'BSE', 'AAEC', 'MS',
       'CS', 'BCHM', 'MATH', 'ENGE', 'AHRM', 'BC', 'ENSC', 'NANO', 'MINE',
       'SPIA', 'PHYS', 'MGT', 'AINS', 'ECON', 'SPAN', 'ITAL', 'JPN',
       'RUS', 'CHN', 'GR', 'GER', 'FR', 'ARBC', 'LAT', 'HEB', 'IDS',
       'ITDS', 'JMC', 'AS', 'NR', 'CLA', 'PHIL', 'FMD', 'LAR', 'HUM',
       'UH', 'HTM', 'LDRS', 'APSC', 'DASC', 'STS', 'PHS', 'RED', 'CMDA',
       'APS', 'AFST', 'WGS', 'ENGR', 'BUS', 'ISE', 'EDCO', 'ENT', 'FA',
       'WATR', 'ME', 'BMES', 'PPWS', 'BDS', 'FST', 'DANC', 'AOE', 'SYSB',
       'PR', 'PSVP', 'CINE', 'CMST', 'ESM', 'ALCE', 'CEM', 'FIW', 'FIN',
       'CHE', 'HORT', 'ADV', 'JUD', 'BMSP', 'BIT', 'CSES', 'CONS', 'STL',
       'EDEP', 'EDCT', 'PM', 'CEE', 'CRIM', 'MKTG', 'NSEG', 'MTRG',
       'BMVS', 'ES', 'GBCB', 'TBMH', 'GIA', 'EDEL', 'PAPA', 'RTM', 'MACR',
       'FL', 'GRAD', 'VM', 'CNST', 'EDHE', 'ASPT', 'EDIT', 'EDP', 'EDRE'],
      dtype=object)

In [73]:
def get_course_no_list(subject):
    filter_list = data[data['Subject'] == subject].sort_values('Course No.')
    return filter_list['Course No.'].unique()

subject = 'CS'
get_course_no_list(subject)

array([1014, 1044, 1054, 1064, 1114, 2064, 2104, 2114, 2144, 2164, 2304,
       2505, 2506, 2974, 3114, 3214, 3274, 3304, 3314, 3414, 3604, 3634,
       3654, 3704, 3714, 3724, 3744, 3754, 3824, 4104, 4114, 4124, 4134,
       4144, 4164, 4204, 4224, 4234, 4254, 4264, 4274, 4284, 4504, 4604,
       4624, 4644, 4654, 4664, 4704, 4774, 4784, 4804, 4824, 4884, 4974,
       4984, 4994, 5014, 5020, 5024, 5040, 5044, 5045, 5046, 5104, 5114,
       5204, 5214, 5234, 5244, 5254, 5264, 5304, 5314, 5486, 5504, 5510,
       5525, 5526, 5544, 5560, 5565, 5566, 5584, 5590, 5594, 5604, 5614,
       5624, 5644, 5664, 5704, 5714, 5724, 5734, 5744, 5754, 5764, 5774,
       5784, 5804, 5805, 5806, 5814, 5824, 5834, 5844, 5854, 5864, 5914,
       5934, 5984, 6104, 6204, 6404, 6524, 6604, 6704, 6724, 6804, 6814,
       6824], dtype=int64)